"""create

Revision ID: 1dff4ba2688e
Revises: 
Create Date: 2019-05-06 04:00:49.397144

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1dff4ba2688e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('barber',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(length=20), nullable=True),
    sa.Column('last_name', sa.String(length=20), nullable=True),
    sa.Column('username', sa.String(length=7), nullable=True),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_barber_first_name'), 'barber', ['first_name'], unique=False)
    op.create_index(op.f('ix_barber_last_name'), 'barber', ['last_name'], unique=False)
    op.create_index(op.f('ix_barber_username'), 'barber', ['username'], unique=True)
    op.create_table('service',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=True),
    sa.Column('description', sa.String(length=300), nullable=True),
    sa.Column('duration', sa.Integer(), nullable=True),
    sa.Column('price', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_service_name'), 'service', ['name'], unique=True)
    op.create_table('reservation',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('reservation_time', sa.DateTime(), nullable=True),
    sa.Column('reservation_date', sa.Date(), nullable=True),
    sa.Column('client_first_name', sa.String(length=20), nullable=True),
    sa.Column('client_last_name', sa.String(length=20), nullable=True),
    sa.Column('client_phone', sa.String(length=10), nullable=True),
    sa.Column('client_email', sa.String(length=50), nullable=True),
    sa.Column('barber_id', sa.Integer(), nullable=True),
    sa.Column('service_id', sa.Integer(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['barber_id'], ['barber.id'], ),
    sa.ForeignKeyConstraint(['service_id'], ['service.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_reservation_client_email'), 'reservation', ['client_email'], unique=False)
    op.create_index(op.f('ix_reservation_client_phone'), 'reservation', ['client_phone'], unique=False)
    op.create_index(op.f('ix_reservation_reservation_date'), 'reservation', ['reservation_date'], unique=False)
    op.create_index(op.f('ix_reservation_reservation_time'), 'reservation', ['reservation_time'], unique=False)
    op.create_index(op.f('ix_reservation_timestamp'), 'reservation', ['timestamp'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_reservation_timestamp'), table_name='reservation')
    op.drop_index(op.f('ix_reservation_reservation_time'), table_name='reservation')
    op.drop_index(op.f('ix_reservation_reservation_date'), table_name='reservation')
    op.drop_index(op.f('ix_reservation_client_phone'), table_name='reservation')
    op.drop_index(op.f('ix_reservation_client_email'), table_name='reservation')
    op.drop_table('reservation')
    op.drop_index(op.f('ix_service_name'), table_name='service')
    op.drop_table('service')
    op.drop_index(op.f('ix_barber_username'), table_name='barber')
    op.drop_index(op.f('ix_barber_last_name'), table_name='barber')
    op.drop_index(op.f('ix_barber_first_name'), table_name='barber')
    op.drop_table('barber')
    # ### end Alembic commands ###
