"""reservation time

Revision ID: 25c232b8fe83
Revises: f76a86f4a1d7
Create Date: 2019-05-05 06:03:53.592701

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '25c232b8fe83'
down_revision = 'f76a86f4a1d7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('reservation', 'date')
    op.drop_column('reservation', 'time')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reservation', sa.Column('time', sa.TIME(), nullable=True))
    op.add_column('reservation', sa.Column('date', sa.DATE(), nullable=True))
    # ### end Alembic commands ###
