"""barbers table

Revision ID: 4a0e77a74c88
Revises: 
Create Date: 2019-05-02 03:04:31.042475

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4a0e77a74c88'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('barber',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(length=20), nullable=True),
    sa.Column('last_name', sa.String(length=20), nullable=True),
    sa.Column('username', sa.String(length=7), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_barber_first_name'), 'barber', ['first_name'], unique=False)
    op.create_index(op.f('ix_barber_last_name'), 'barber', ['last_name'], unique=False)
    op.create_index(op.f('ix_barber_username'), 'barber', ['username'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_barber_username'), table_name='barber')
    op.drop_index(op.f('ix_barber_last_name'), table_name='barber')
    op.drop_index(op.f('ix_barber_first_name'), table_name='barber')
    op.drop_table('barber')
    # ### end Alembic commands ###
