"""reservation confirmed_status field

Revision ID: b61fec7768d8
Revises: 1dff4ba2688e
Create Date: 2019-05-09 15:40:31.332222

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b61fec7768d8'
down_revision = '1dff4ba2688e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reservation', sa.Column('confirmed_status', sa.Boolean(), nullable=True))
    op.create_index(op.f('ix_reservation_confirmed_status'), 'reservation', ['confirmed_status'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_reservation_confirmed_status'), table_name='reservation')
    op.drop_column('reservation', 'confirmed_status')
    # ### end Alembic commands ###
