"""barber password

Revision ID: f47f77d53439
Revises: de1c54738af0
Create Date: 2019-05-02 15:26:27.269955

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f47f77d53439'
down_revision = 'de1c54738af0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('barber', sa.Column('password_hash', sa.String(length=128), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('barber', 'password_hash')
    # ### end Alembic commands ###
